# **Linear systems of equations**

This notebooks shows how to implement the following methods
- `jacobi`
- `gseid`
- `sor`

In [1]:
# this is not a necessary import, I just have it here because vscode requires it
# to run the script in the same directory as the script
# and not the directory where the script is located

import sys

sys.path.append("..")

In [2]:
import numpy as np

---

## **Jacobi method**

The Jacobi method is an iterative technique for solving systems of linear equations of the form $Ax = b$. 

**How It Works**

The method decomposes the coefficient matrix $A$ into its diagonal component $D$ and the remainder $R = L + U$ (lower and upper triangular parts). It then iteratively computes:

$$x^{(k+1)} = D^{-1}(b - (L+U)x^{(k)})$$

**Example**

In the next cell, we solve a 5×5 linear system using the Jacobi method:
- Matrix $A$ is a 5×5 coefficient matrix
- Vector $b$ is our right-hand side
- We start with initial guess $x_0 = [1, 2, 3, 4, 5]$
- The relaxation parameter is set to 1.6

The solution converges to the values shown in the output.


In [3]:
from functions.linear import jacobi

A = np.array([
     [3, -1, 0, 0, 0],
     [-1, 5, 4, 0, 0],
     [0, 4, 6, -2, 0],
     [0, 0, -2, 8, 1],
     [0, 0, 0, 1, 11],
])

b = [3,0,1,-1,3]

x0 = np.array([i for i in range(1,6)])
r,_,_ = jacobi(A, b, x0)

print(r)

[[ 1.0962]
 [ 0.2886]
 [-0.0866]
 [-0.1828]
 [ 0.2893]]


---

## **Gauss-Seidel method**

The Gauss-Seidel method is an iterative technique for solving systems of linear equations of the form $Ax = b$.

**How It Works**

The method improves upon Jacobi by immediately using updated values as they are calculated. It decomposes matrix $A$ into diagonal ($D$), strictly lower triangular ($L$) and strictly upper triangular ($U$) components, then iteratively computes:

$$x^{(k+1)} = (D+L)^{-1}(b - Ux^{(k)})$$

**Example**

In the next cell, we solve the same 5×5 linear system using the Gauss-Seidel method:
- Matrix $A$ is our 5×5 coefficient matrix
- Vector $b$ is the right-hand side
- Initial guess $x_0 = [1, 2, 3, 4, 5]$
- Relaxation parameter is set to 1.6

The solution converges to the values shown in the output.


In [4]:
from functions.linear import gseid

A = np.array([
     [3, -1, 0, 0, 0],
     [-1, 5, 4, 0, 0],
     [0, 4, 6, -2, 0],
     [0, 0, -2, 8, 1],
     [0, 0, 0, 1, 11],
])

b = [3,0,1,-1,3]

x0 = np.array([i for i in range(1,6)])
r,_,_ = gseid(A, b, x0)

print(r)

[[ 1.0962]
 [ 0.2886]
 [-0.0866]
 [-0.1828]
 [ 0.2893]]


---

## **Successive Over-Relaxation (SOR) method**

The Successive Over-Relaxation (SOR) method is an iterative technique for solving systems of linear equations of the form $Ax = b$.

**How It Works**

The SOR method is a modification of the Gauss-Seidel method that introduces a relaxation parameter $\omega$ to accelerate convergence. It decomposes matrix $A$ into diagonal ($D$), strictly lower triangular ($L$), and strictly upper triangular ($U$) components, then iteratively computes:

$$x^{(k+1)} = (1-\omega)x^{(k)} + \omega(D+\omega L)^{-1}(b - Ux^{(k)} - (1-\omega)Dx^{(k)})$$

When $\omega = 1$, SOR reduces to the Gauss-Seidel method.

**Example**

In the next cell, we solve the same 5×5 linear system using the SOR method:
- Matrix $A$ is our 5×5 coefficient matrix 
- Vector $b$ is the right-hand side
- Initial guess $x_0 = [1, 2, 3, 4, 5]$
- Relaxation parameter $\omega = 1.2$

The solution converges to the values shown in the output.

In [88]:
from functions.linear import sor

A = np.array([
     [3, -1, 0, 0, 0],
     [-1, 5, 4, 0, 0],
     [0, 4, 6, -2, 0],
     [0, 0, -2, 8, 1],
     [0, 0, 0, 1, 11],
])

b = np.array([3,0,1,-1,3]).reshape(-1,1)

x0 = np.zeros(5)
r,_,_ = sor(A, b, x0, omega=1.29)

print(r)


[[ 1.0962]
 [ 0.2886]
 [-0.0866]
 [-0.1828]
 [ 0.2893]]
